# Introdução

O presente relatório descreve a aplicação do método _Linear Programming Discriminant Analysis (LPDA)_ conforme proposto no artigo intitulado **"LPDA: A new classification method based on linear programming"**. O objetivo principal deste trabalho é desenvolver um modelo de classificação binária utilizando o LPDA em um conjunto de dados previamente selecionado, disponível na pasta "data".

O artigo também apresenta uma biblioteca em R que oferece métodos para a implementação do LPDA. A documentação completa dessa biblioteca pode ser encontrada no CRAN, no seguinte endereço: [pacote lpda](https://cran.r-project.org/web/packages/lpda/index.html).

No entanto, devido às complexidades associadas à conversão do código R para Python e às particularidades das estruturas de dados utilizadas pela biblioteca, optou-se por empregar a biblioteca [Pulp](https://coin-or.github.io/pulp/). Essa biblioteca possibilita a descrição iterativa do problema de programação linear a ser resolvido, oferecendo a opção de utilizar o solver de preferência do usuário. Outras ferramentas, como [AMPL](https://ampl.com/), seguem uma abordagem semelhante.

# Metodologia

A implementação do LPDA utilizando a biblioteca Pulp permitiu resolver o problema de programação linear, encontrando a solução ótima. Os coeficientes do plano H descritos no artigo, bem como a constante 'b', foram obtidos como resultado. Adicionalmente, foram desenvolvidos métodos para armazenar esses valores em disco, possibilitando sua reutilização posterior.

Com o arquivo do modelo armazenado, foi possível criar um servidor de aplicação que oferece duas rotas principais:

1. **Treinamento:** A rota `POST /heart/train` realiza o treinamento do modelo. Exemplo de chamada:
   ```bash
   !curl --request POST --url http://localhost:8080/heart/train
2. **Predição:** A rota `POST /heart/predict` permite realizar previsões com base no modelo treinado. Exemplo de chamada:

   ```bash
   !curl --request POST \
   --url http://localhost:8080/heart/predict \
   --header 'Content-Type: application/json' \
   --data '{
    "age": 19,
    "sex": 0,
    "cp": 1,
    "trestbps": 120,
    "chol": 204,
    "fbs": 0,
    "restecg": 0,
    "thalach": 172,
    "exang": 0,
    "oldpeak": 1.4,
    "slope": 2,
    "ca": 0,
    "thal": 2
   }'

### Como Rodar

1. Instalar Python >= 3.9 ([Download Python](https://www.python.org/))
2. Instalar Poetry ([Download Poetry](https://python-poetry.org/))
3. `cd code`
4. `poetry install`
5. `poetry shell`

### Rodar como servidor de aplicação:

- `python .\src\main.py`

### Rodar como aplicação standalone para validação do modelo:

- `python .\src\test.py`


In [1]:
import pandas as pd 
import numpy as np
from train.lpda import lpda, simple_predict, predict
import matplotlib.pyplot as plt
import seaborn as sb
from test import main

In [21]:
file = '..\data\heart_disease\heart.csv'
df = pd.read_csv(file)
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\elisb\AppData\Local\Temp\ipykernel_2864\1262763081.py:1: SyntaxWarning: invalid escape sequence '\d'
  file = '..\data\heart_disease\heart.csv'


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [20]:
result_heart = main(df_heart, 'target')
print(result_heart)

Solution: 
	a = [0.013748104, 1.1251695, 0.0, 0.0, 0.0039203577, 0.0, 0.0, 0.0, 1.3843964, 0.46359572, 0.0, 0.70430837, 0.45532538]
	b = 4.9093753


Test set: 
	X_test = [[5.90e+01 1.00e+00 3.00e+00 1.60e+02 2.73e+02 0.00e+00 0.00e+00 1.25e+02 0.00e+00 0.00e+00 2.00e+00 0.00e+00 2.00e+00]
 [4.60e+01 1.00e+00 0.00e+00 1.20e+02 2.49e+02 0.00e+00 0.00e+00 1.44e+02 0.00e+00 8.00e-01 2.00e+00 0.00e+00 3.00e+00]
 [6.40e+01 1.00e+00 2.00e+00 1.40e+02 3.35e+02 0.00e+00 1.00e+00 1.58e+02 0.00e+00 0.00e+00 2.00e+00 0.00e+00 2.00e+00]
 [5.80e+01 1.00e+00 0.00e+00 1.28e+02 2.16e+02 0.00e+00 0.00e+00 1.31e+02 1.00e+00 2.20e+00 1.00e+00 3.00e+00 3.00e+00]
 [6.40e+01 1.00e+00 2.00e+00 1.25e+02 3.09e+02 0.00e+00 1.00e+00 1.31e+02 1.00e+00 1.80e+00 1.00e+00 0.00e+00 3.00e+00]
 [5.50e+01 1.00e+00 0.00e+00 1.60e+02 2.89e+02 0.00e+00 0.00e+00 1.45e+02 1.00e+00 8.00e-01 1.00e+00 1.00e+00 3.00e+00]
 [4.70e+01 1.00e+00 2.00e+00 1.08e+02 2.43e+02 0.00e+00 1.00e+00 1.52e+02 0.00e+00 0.00e+00 2.00e+00 0.00e+00 

# Resultados

# Conclusão